### PR TITLE
New icon

### PR DESCRIPTION
**Pull request by gingerbeardman**
icon preview

icon preview

### CODE REVIEW

**Comment by gingerbeardman** [comment]
Please let me know if it's worth me new images for all other image assets,  e.g. toolbar buttons

**Comment by skovatch** [comment]
I think this looks good. If you want to make new buttons, I'll have a look. They haven't changed in a long time, so an update would be good.

**Comment by Lordsnooty05** [comment]
Guys looks good the icon I mean. Good to see you guys working together. So far everything is working good for me and in fact I think GIA is downloading much quicker......so skovatch, thanks for all you are doing for this Superb App

**Comment by naq59** [comment]
It looks and works fine but the main point is GIA is up working again and does seem slightly faster. You´ve earned my eternal gratitude for that and I´m sure I speak for many other users.

**Comment by gingerbeardman** [comment]
OK @skovatch see https://github.com/Ascoware/get-iplayer-automator/issues/33

**Pull request merged**
